# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

import datetime
import os
import sys

from act.core.gui.plots.base_table import BaseTable
from act.core.utils.units import kg


class SimInfoTable(BaseTable):
    """
    A table that displays general information about the ACT analysis.

    This table presents key metadata about the analysis session, including:
    - Report generation timestamp and user
    - Version control information (commit hash and diff)
    - Command line details used to run the analysis
    - System summary information (device count, total carbon)
    - Performance metrics (analysis execution time)

    The table provides context for the analysis results and helps with reproducibility
    by capturing the environment and configuration used for the analysis run.
    """

    def __init__(self, act, weight_unit=kg, *args, show_relative_path=False, **kwargs):
        """
        Initialize the Analysis Info Table with ACT analysis data.

        Args:
            act: The ACT analysis object containing results data and timing information.
            weight_unit (Unit, optional): The unit to use for displaying weight values.
                Defaults to kilograms (kg).
            *args: Variable length argument list passed to BaseTable.
            show_relative_path (bool, optional): Whether to show only the basename of the
                command line binary path instead of the full path. Defaults to False.
            **kwargs: Arbitrary keyword arguments passed to BaseTable.

        The constructor initializes the table with the provided ACT analysis object and
        configuration options, then immediately calls plot() to populate the table data.
        """
        self.act = act
        self.weight_unit = weight_unit
        self.show_relative_path = show_relative_path
        super().__init__(*args, **kwargs)
        self.plot()

    def plot(self):
        """
        Populate the table with analysis information data.

        This method sets up the table header and populates the data dictionary with
        key information about the analysis, including:
        - Report generation details (timestamp, user)
        - Version control information (commit hash, diff)
        - Command line information
        - System metrics (device count, total carbon)
        - Performance metrics (analysis time)
        """
        self.header = ["Simulation Info", "Value"]
        now = datetime.datetime.now()
        elapsed_time = self.act.end_time - self.act.start_time

        self.data_dict = {
            "Report Generated": now.strftime("%m/%d/%Y %H:%M:%S"),
            "Generated By": os.environ.get("USER", ""),
            "Command Line Binary": sys.argv[0]
            if not self.show_relative_path
            else os.path.basename(sys.argv[0]),
            "Command Line Arguments": " ".join(sys.argv[1:]),
            "Total System Devices": len(self.act.bom.devices),
            "Total Carbon": "%.2f "
            % self.act.results.total_carbon.total().to(self.weight_unit).m
            + format(self.weight_unit.units, "~"),
            "ACT Analysis Time": "%.4f" % elapsed_time.total_seconds() + " s",
        }

    def get_html(self):
        """
        Generate the HTML representation of the analysis info table.

        Overrides the parent class method to apply left alignment to all columns
        in the table for better readability of the analysis information.

        Returns:
            str: HTML representation of the table with left-aligned columns.
        """
        return super().get_html(align={k: "l" for k in self.header})
