# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the license found in the
# LICENSE file in the root directory of this source tree.

name: Onshoring fabrication supply chain
compatible_with: ["server/dellr740/top.yaml"]
scaling_paths:
  ssd:
    location: usa
  dram:
    location: usa
  cpu:
    location: usa
